### ISSUE TITLE
need include option

### ISSUE THREAD

**Issue by hyzhak** [jackypan1989/del-webpack-plugin#1]
Very often I could put unneeded files into a single directory ("trash"), which I'd like to remove. So it would be is much easy to include single `"trash"` directory to the plugin process, than enum every created file in exclude option.

**Comment by jackypan1989** [comment]
WIP

**Comment by jackypan1989** [comment]
fixed, pls update to 1.0.2

**Comment by jackypan1989** [comment]
@hyzhak

**Comment by petermetz** [comment]
@jackypan1989 Is there a breaking change between 1.0.1 and 1.0.2? 
1.0.2 throws unless I specify the `include` configuration property as an empty array.

**Comment by jackypan1989** [comment]
bump to v1.0.3
https://github.com/jackypan1989/del-webpack-plugin/releases/tag/v1.0.3

**Comment by jackypan1989** [comment]
@petermetz
