### ISSUE TITLE
npmjs.org readme issue

### ISSUE THREAD

**Issue by nickensoul** [jackypan1989/del-webpack-plugin#2]
Look at [this](https://www.npmjs.com/package/del-webpack-plugin#usage-in-your-webpack-config) section:
```const DelWebpackPlugin = require('clean-webpack-plugin')```
Seems it's a typo.

**Comment by jackypan1989** [comment]
thank you, it will be fixed at the next release

**Comment by jackypan1989** [comment]
fix in https://github.com/jackypan1989/del-webpack-plugin/releases/tag/v1.0.2
