### ISSUE TITLE
Directories with new files not excluded automatically

### ISSUE THREAD

**Issue by Desp163** [jackypan1989/del-webpack-plugin#3]
Hello.
Plugin by default removes all directories inside /build dir, because they're not listed in "added files" but matched by '**' includes.

For example, at start i have clean /build dir.
My webpack created sprites in /build/sprites/1.png dir.
And then plugin removes /build/sprites dir with my newly creates sprite.

Thus, it's needed to automatically exclude not only files, but also directories which has files which was created.

**Comment by jackypan1989** [comment]
you can set the folder you dont want to remove
```
{
  plugins: [
    new DelWebpackPlugin({
      info: true,
      exclude: ['sprites']
    })
  ]
}
```

**Comment by Desp163** [comment]
Yes. I can manually exclude all directories i have (a lot).
But it means that this plugin does not allow to have any dirs in ./build by default. It will mistakenly delete them right after they're created.

**Comment by jackypan1989** [comment]
thank you @Igonato

**Comment by jackypan1989** [comment]
readme updated

**Comment by Igonato** [comment]
Readme update isn't a bug fix. Also, this isn't that good of a solution, files without a dot in the filename won't be deleted for example. We need some extra logic to keep the directories.

**Comment by jackypan1989** [comment]
it's just the logic of del lib
