### ISSUE TITLE
files in output will been default exclude?

### ISSUE THREAD

**Issue by qinyang912** [jackypan1989/del-webpack-plugin#8]
I want to delete files in output path, but I see the source code has auto ignore the files in output path

```js
// exclude files
const excludePatterns = [
  outputPath,
  ...this.options.exclude.map(name => path.join(outputPath, name)),
  ...assetNames.map(name => path.join(outputPath, name))
]
```

**Comment by AMontagu** [comment]
Look like my problem.
I need to delete a file generated by webpack but it seem ignored by this plugin:

```
===== Del Webpack Plugin ===
Added files:
tmp/something.js
main.js

Deleted files:
tmp
============================
```

**Comment by qinyang912** [comment]
@jackypan1989  yes
I'm using webpack to develop a library, the webpack config look like:

```js
{
  entry: {
    'main': './src/index.js',
    'core': ['a.scss', 'b.scss']
  },
  output: {
    filename: '[name].js',
    library: 'Test',
    path: './dist'
  },
  plugins: [
    new ExtractTextPlugin({
      filename: '[name].css',
    })
  ]
}
```
when build, will generate three files in output path:
```
main.js
core.js
core.css
```
I wanna customize the name of css file, so I must import all scss files in an entry, but this will generate a useless javascript file, so I wanna delete `core.js`

**Comment by AMontagu** [comment]
almost the same for me. I use webpack to bundle multiple web application but some are just html/css/js so no need of main.js file created by webpack.

**Comment by jackypan1989** [comment]
I will checkout this issue soon.

**Comment by qinyang912** [comment]
@jackypan1989 thanks.

**Comment by jackypan1989** [comment]
https://github.com/jackypan1989/del-webpack-plugin/releases/tag/v1.1.0
You can set keepGeneratedAssets to ```false``` now.

Notice: you may do something exclude pattern to keep files
